name: Destroy infrastructure - Terraform

on:
  workflow_dispatch:

jobs:
  deploy-env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Simple task
        run: echo "Hello, world!"